### ISSUE TITLE
Where did I make a mistake?

### ISSUE THREAD

**Issue by thiraphat98** [dazedanon/DazedMTLTool#12]
![image](https://github.com/dazedanon/DazedMTLTool/assets/88649750/0a7c9626-1922-410b-878a-504daeb66ce2)

**Comment by Kryomancer** [comment]
If you go to the [billing page on OpenAI](https://platform.openai.com/account/billing/overview), do you have any credit left? If not, you'll need to add some. If you do have credit left and it's still failing then it's probably because your account has a monthly spending limit set: Check on the [usage page](https://platform.openai.com/usage) and see if your monthly bill at top right has hit 100%, if so, you'll need to hit increase limit and just put in a higher limit on the page that opens.

**Comment by thiraphat98** [comment]
> If you go to the [billing page on OpenAI](https://platform.openai.com/account/billing/overview), do you have any credit left? If not, you'll need to add some. If you do have credit left and it's still failing then it's probably because your account has a monthly spending limit set: Check on the [usage page](https://platform.openai.com/usage) and see if your monthly bill at top right has hit 100%, if so, you'll need to hit increase limit and just put in a higher limit on the page that opens.

Thanks, it worked, but it doesn't seem to work with Thai because it's 10 times more expensive than English.
